# Generated by Django 5.2.4 on 2025-07-11 05:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='agentconfig',
            name='memory_enabled',
        ),
        migrations.RemoveField(
            model_name='agentconfig',
            name='supervisor_prompt',
        ),
        migrations.RemoveField(
            model_name='agentconfig',
            name='verification_enabled',
        ),
        migrations.RemoveField(
            model_name='agenttype',
            name='system_prompt',
        ),
        migrations.RemoveField(
            model_name='agenttype',
            name='tools',
        ),
        migrations.RemoveField(
            model_name='database',
            name='description',
        ),
        migrations.RemoveField(
            model_name='message',
            name='tool_calls',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='is_enabled',
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='agent_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agentsapp.agenttype'),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='system_prompt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='tools',
            field=models.ManyToManyField(blank=True, to='agentsapp.tool'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='_metadata',
            field=models.TextField(blank=True, db_column='metadata', null=True),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='api_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='llmmodel',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='agentconfig',
            name='llm_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agentsapp.llmmodel'),
        ),
        migrations.AlterField(
            model_name='agenttype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='thread_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='database',
            name='connection_string',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='api_base',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='max_tokens',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='model_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='provider',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='temperature',
            field=models.FloatField(default=0.7),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preference_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='value',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userpreference',
            unique_together={('profile', 'preference_type', 'value')},
        ),
    ]
